### PR TITLE
add python version of uc5, tested on Terrascope

### PR DESCRIPTION
**Pull request by jdries**
Added Python version of UC5 (JRC), tested on geotrellis/Terrascope/VITO backend. Also added process graph generated by Python code.
Known differences to original:
- run_udf has to be invoked in a callback to apply_dimension, otherwise this is not scalable
- the udf uses an open source version of szavitky golay, may need to be tuned or replaced with pyjeo if available
- spatial bbox is not defined: geotrellis backend derives it from the polygons
- on terrascope, a precomputed NDVI layer is available. Computing the NDVI would work as well.
- polygons are provided in the request, Terrascope also supports reading from file or url (so linking to github might work)
- no filtering on properties: Terrascope supports some of it, but was not strictly required for the actual use case, so better to have a graph that is more generic?

Overall, it was very easy to 'port' the graph to a different backend.

### CODE REVIEW

**Review by kempenep — APPROVED** [review]
Thanks for adding this front end Python code. As we did not integrate the front end yet, I cannot test on the JEODPP.

**Review by kempenep — CHANGES_REQUESTED** [review]
For the udf implementation: it should implement the algorithm from Jin Chen (doi:10.1016/j.rse.2004.03.014), which applies an iterative Savitzky-Golay filter. This will be important if we want to be able to compare the outputs from the different backends.

**Comment by m-mohr** [comment]
Thanks a lot, also for providing the details on changes. Could you send me a result via e-mail so that I can include it in the deliverable (if I do so, not sure yet).

**Comment by jdries** [comment]
I'll merge this PR: for the UDF, I can integrate any algorithm as long as it's available, so maybe it's better to also wait till you open source pyjeo, and then we can use that. Or should we add a note saying that another savitzky golay should be used in practice?

**Comment by kempenep** [comment]
> I'll merge this PR: for the UDF, I can integrate any algorithm as long as it's available, so maybe it's better to also wait till you open source pyjeo, and then we can use that. Or should we add a note saying that another savitzky golay should be used in practice?

Good news for the pyjeo, we just received the approval to license as GPLv3! 

As for the UDF, you can still use the Savitzky Golay from scipy (or any other). It is just that it is called iteratively, Here some "pseudo" Python code with input the input image (array):
```
savgol = savgolay(input, nl=7, nr=7, m=2, pad='replicate') #use Savitzky-Golay filter implementation of your choice here
for loop in range(0, 4):
    savgol[savgol < input] = input #use Savitzky-Golay filter implementation of your choice here
    savgol = savgolay(savgol, nl=4, nr=4, m=6)
```
where the arguments in the Savitzky-Golay filter are:
nl – Number of leftward (past) data points used in Savitzky- Golay filter)
nr – Number of rightward (future) data points used in Savitzky- Golay filter)
m – order of the smoothing polynomial in Savitzky-Golay filter, also equal to the highest conserved moment; usual values are m=2 or m=4)

**Pull request merged**
